-- OneToFour: banco inicial ampliado.
-- Ejecutar una sola vez después de 01_crear_tablas.sql.
-- Las preguntas tienen IDs 101-220 para no colisionar con el banco inicial.

INSERT INTO workspace.quiz.preguntas
SELECT * FROM VALUES
(101,'¿En qué año comenzó la Revolución francesa?','1776','1789','1812','1848','B','Historia','Fácil','La Revolución francesa comenzó en 1789.'),
(102,'¿Qué civilización construyó Machu Picchu?','Maya','Azteca','Inca','Romana','C','Historia','Fácil','Machu Picchu fue construido por la civilización inca.'),
(103,'¿Quién fue el primer emperador romano?','Julio César','Augusto','Nerón','Trajano','B','Historia','Medio','Augusto fue el primer emperador romano.'),
(104,'¿Qué tratado puso fin oficialmente a la Primera Guerra Mundial con Alemania?','Tratado de Utrecht','Tratado de Versalles','Tratado de Tordesillas','Tratado de París','B','Historia','Medio','El Tratado de Versalles se firmó en 1919.'),
(105,'¿Qué ciudad fue capital del Imperio bizantino?','Atenas','Roma','Constantinopla','Alejandría','C','Historia','Fácil','Constantinopla fue la capital del Imperio bizantino.'),
(106,'¿En qué siglo llegó Cristóbal Colón a América?','XIV','XV','XVI','XVII','B','Historia','Fácil','Colón llegó a América en 1492, en el siglo XV.'),
(107,'¿Qué faraón está asociado a una famosa tumba descubierta en 1922?','Ramsés II','Tutankamón','Akenatón','Keops','B','Historia','Fácil','La tumba de Tutankamón fue descubierta por Howard Carter en 1922.'),
(108,'¿Qué acontecimiento ocurrió en 1066 en Inglaterra?','La conquista normanda','La Revolución industrial','La firma de la Carta Magna','La peste negra','A','Historia','Medio','Guillermo el Conquistador venció en Hastings en 1066.'),
(109,'¿Qué imperio tenía su centro político en Tenochtitlan?','Inca','Azteca','Persa','Otomano','B','Historia','Fácil','Tenochtitlan fue la capital del Imperio azteca.'),
(110,'¿Qué documento de 1215 limitó el poder del rey de Inglaterra?','Código Napoleónico','Carta Magna','Edicto de Milán','Acta de Unión','B','Historia','Medio','La Carta Magna fue acordada en 1215.'),
(111,'¿Qué película ganó el Óscar a mejor película en 1994?','Forrest Gump','Pulp Fiction','Titanic','Braveheart','A','Cine','Medio','Forrest Gump ganó el Óscar a mejor película de 1994.'),
(112,'¿Quién dirigió Jurassic Park?','Steven Spielberg','James Cameron','Ridley Scott','Peter Jackson','A','Cine','Fácil','Steven Spielberg dirigió Jurassic Park.'),
(113,'¿En qué película aparece el personaje Jack Dawson?','Avatar','Titanic','Gladiator','Matrix','B','Cine','Fácil','Jack Dawson es uno de los protagonistas de Titanic.'),
(114,'¿Qué saga cinematográfica está ambientada en la Tierra Media?','Star Wars','Harry Potter','El Señor de los Anillos','Indiana Jones','C','Cine','Fácil','El Señor de los Anillos está ambientado en la Tierra Media.'),
(115,'¿Quién interpretó a Neo en Matrix?','Matt Damon','Keanu Reeves','Brad Pitt','Christian Bale','B','Cine','Fácil','Keanu Reeves interpretó a Neo.'),
(116,'¿Qué película de animación presenta a Woody y Buzz Lightyear?','Shrek','Toy Story','Cars','Up','B','Cine','Fácil','Woody y Buzz son personajes de Toy Story.'),
(117,'¿Qué director creó la trilogía original de El Padrino?','Francis Ford Coppola','Martin Scorsese','Stanley Kubrick','Christopher Nolan','A','Cine','Medio','Francis Ford Coppola dirigió El Padrino.'),
(118,'¿Qué película ganó el Óscar a mejor película en 2020?','1917','Parásitos','Joker','Érase una vez en Hollywood','B','Cine','Medio','Parásitos ganó el Óscar a mejor película en la ceremonia de 2020.'),
(119,'¿En qué película aparece el hotel Overlook?','El resplandor','Psicosis','Alien','Scream','A','Cine','Medio','El hotel Overlook es el escenario principal de El resplandor.'),
(120,'¿Qué actor interpreta a Indiana Jones en las películas clásicas?','Tom Hanks','Harrison Ford','Robert De Niro','Michael Douglas','B','Cine','Fácil','Harrison Ford interpreta a Indiana Jones.'),
(121,'¿Cuál es el símbolo químico del oro?','Ag','Au','Fe','Go','B','Ciencia','Fácil','Au es el símbolo químico del oro.'),
(122,'¿Qué órgano bombea la sangre por el cuerpo?','Pulmón','Hígado','Corazón','Riñón','C','Ciencia','Fácil','El corazón bombea la sangre por el sistema circulatorio.'),
(123,'¿Qué planeta tiene los anillos más visibles del sistema solar?','Marte','Saturno','Venus','Mercurio','B','Ciencia','Fácil','Saturno destaca por su sistema de anillos.'),
(124,'¿Cuál es la unidad básica de la vida?','Átomo','Tejido','Célula','Órgano','C','Ciencia','Fácil','La célula es la unidad básica de los seres vivos.'),
(125,'¿Qué gas absorben las plantas durante la fotosíntesis?','Oxígeno','Nitrógeno','Dióxido de carbono','Helio','C','Ciencia','Fácil','Las plantas utilizan dióxido de carbono en la fotosíntesis.'),
(126,'¿Qué fuerza mantiene a los planetas en órbita alrededor del Sol?','Magnetismo','Gravedad','Fricción','Electricidad','B','Ciencia','Fácil','La gravedad mantiene los cuerpos en órbita.'),
(127,'¿Cuál es aproximadamente la velocidad de la luz en el vacío?','300 km/s','3.000 km/s','300.000 km/s','3.000.000 km/s','C','Ciencia','Medio','La luz viaja aproximadamente a 300.000 km/s en el vacío.'),
(128,'¿Qué partícula tiene carga eléctrica negativa?','Protón','Neutrón','Electrón','Fotón','C','Ciencia','Fácil','El electrón tiene carga eléctrica negativa.'),
(129,'¿Qué científico formuló las leyes del movimiento y la gravitación clásica?','Newton','Darwin','Pasteur','Faraday','A','Ciencia','Medio','Isaac Newton formuló las leyes del movimiento y la gravitación universal.'),
(130,'¿Qué tipo de animal es una ballena?','Pez','Reptil','Mamífero','Anfibio','C','Ciencia','Fácil','Las ballenas son mamíferos marinos.'),
(131,'¿Cuántos jugadores tiene un equipo de fútbol en el campo al comenzar un partido?','9','10','11','12','C','Deporte','Fácil','Un equipo de fútbol juega con once jugadores en el campo.'),
(132,'¿En qué deporte se utiliza un volante o shuttlecock?','Tenis','Bádminton','Balonmano','Hockey','B','Deporte','Fácil','El volante es el proyectil utilizado en bádminton.'),
(133,'¿Cuántos anillos tiene el símbolo olímpico?','4','5','6','7','B','Deporte','Fácil','El símbolo olímpico está formado por cinco anillos.'),
(134,'¿Qué país ganó el Mundial de fútbol de 2010?','España','Brasil','Alemania','Argentina','A','Deporte','Fácil','España ganó el Mundial de 2010.'),
(135,'¿En qué deporte se disputa Wimbledon?','Golf','Tenis','Rugby','Críquet','B','Deporte','Fácil','Wimbledon es uno de los grandes torneos de tenis.'),
(136,'¿Cuántos puntos vale un tiro libre en baloncesto?','1','2','3','4','A','Deporte','Fácil','Un tiro libre convertido vale un punto.'),
(137,'¿Qué distancia tiene una maratón oficial?','40 km','41,195 km','42,195 km','45 km','C','Deporte','Medio','La distancia oficial de una maratón es 42,195 km.'),
(138,'¿En qué deporte se usa una espada, florete o sable?','Esgrima','Gimnasia','Remo','Ciclismo','A','Deporte','Fácil','La esgrima utiliza espada, florete y sable.'),
(139,'¿Qué pieza se mueve en forma de L en ajedrez?','Alfil','Torre','Caballo','Rey','C','Deporte','Fácil','El caballo se mueve en forma de L.'),
(140,'¿Cuántos sets debe ganar un jugador para vencer normalmente un partido masculino de Grand Slam?','2','3','4','5','B','Deporte','Medio','En los individuales masculinos de Grand Slam se juega al mejor de cinco sets.'),
(141,'¿Qué cantante publicó el álbum Thriller?','Michael Jackson','Prince','Elton John','David Bowie','A','Corazón','Fácil','Thriller es un álbum de Michael Jackson.'),
(142,'¿Qué grupo británico lanzó Bohemian Rhapsody?','The Beatles','Queen','Oasis','Coldplay','B','Corazón','Fácil','Bohemian Rhapsody fue publicada por Queen.'),
(143,'¿Qué artista es conocido por la canción Like a Prayer?','Madonna','Cher','Adele','Beyoncé','A','Corazón','Fácil','Like a Prayer es una canción de Madonna.'),
(144,'¿Qué cantante protagonizó la película A Star Is Born de 2018 junto a Bradley Cooper?','Lady Gaga','Rihanna','Taylor Swift','Katy Perry','A','Corazón','Fácil','Lady Gaga protagonizó A Star Is Born de 2018.'),
(145,'¿Qué grupo español popularizó la canción 20 de abril?','Celtas Cortos','Mecano','Hombres G','La Unión','A','Corazón','Medio','20 de abril es una canción de Celtas Cortos.'),
(146,'¿Qué cantante es conocida como la Reina del Pop?','Madonna','Dua Lipa','Shakira','Ariana Grande','A','Corazón','Fácil','Madonna es ampliamente conocida como la Reina del Pop.'),
(147,'¿Qué dúo español formaban Alaska y Nacho Canut?','Fangoria','Ella Baila Sola','Amistades Peligrosas','Azúcar Moreno','A','Corazón','Medio','Fangoria está formado por Alaska y Nacho Canut.'),
(148,'¿Qué cantante lanzó el álbum 21?','Adele','Sia','Pink','Shakira','A','Corazón','Fácil','21 es un álbum de Adele.'),
(149,'¿Qué grupo sueco ganó Eurovisión en 1974 con Waterloo?','ABBA','Roxette','Ace of Base','Europe','A','Corazón','Fácil','ABBA ganó Eurovisión en 1974 con Waterloo.'),
(150,'¿Qué cantante colombiana publicó Hips Don’t Lie?','Shakira','Karol G','Rosalía','Paulina Rubio','A','Corazón','Fácil','Hips Don’t Lie es una canción de Shakira.'),
(151,'¿Cuál es el animal terrestre más grande?','Elefante africano','Jirafa','Rinoceronte','Hipopótamo','A','Naturaleza','Fácil','El elefante africano es el animal terrestre más grande.'),
(152,'¿Qué animal es conocido por cambiar de color para camuflarse?','Camaleón','Cebra','Pingüino','Koala','A','Naturaleza','Fácil','Los camaleones pueden cambiar de color y patrón.'),
(153,'¿Cuál es el árbol más alto conocido?','Secuoya costera','Olivo','Baobab','Arce','A','Naturaleza','Medio','Las secuoyas costeras incluyen los árboles más altos conocidos.'),
(154,'¿Qué mamífero pone huevos?','Delfín','Ornitorrinco','León','Murciélago','B','Naturaleza','Fácil','El ornitorrinco es un mamífero monotremo que pone huevos.'),
(155,'¿Qué felino es el más grande del mundo?','Leopardo','Tigre','Guepardo','Lince','B','Naturaleza','Fácil','El tigre es el felino de mayor tamaño.'),
(156,'¿Qué proceso transforma una oruga en mariposa?','Germinación','Metamorfosis','Fotosíntesis','Fermentación','B','Naturaleza','Fácil','La transformación de oruga a mariposa forma parte de la metamorfosis.'),
(157,'¿Cuál es el océano más grande de la Tierra?','Atlántico','Índico','Pacífico','Ártico','C','Naturaleza','Fácil','El Pacífico es el océano más extenso.'),
(158,'¿Qué animal tiene tres corazones?','Pulpo','Caballo','Águila','Tortuga','A','Naturaleza','Medio','Los pulpos tienen tres corazones.'),
(159,'¿Qué gas constituye la mayor parte de la atmósfera terrestre?','Oxígeno','Nitrógeno','Dióxido de carbono','Argón','B','Naturaleza','Fácil','El nitrógeno representa aproximadamente el 78% de la atmósfera.'),
(160,'¿Qué bioma se caracteriza por temperaturas muy bajas y permafrost?','Sabana','Tundra','Selva tropical','Pradera','B','Naturaleza','Medio','La tundra presenta bajas temperaturas y zonas de permafrost.'),
(161,'¿Cuál es la capital de Canadá?','Toronto','Vancouver','Ottawa','Montreal','C','Geografía','Fácil','Ottawa es la capital de Canadá.'),
(162,'¿Qué río atraviesa Egipto?','Amazonas','Nilo','Danubio','Misisipi','B','Geografía','Fácil','El Nilo atraviesa Egipto de sur a norte.'),
(163,'¿Cuál es el país más grande del mundo por superficie?','China','Canadá','Rusia','Estados Unidos','C','Geografía','Fácil','Rusia es el país con mayor superficie.'),
(164,'¿Qué cordillera separa tradicionalmente Europa de Asia?','Andes','Urales','Alpes','Himalaya','B','Geografía','Medio','Los montes Urales forman una frontera geográfica tradicional entre Europa y Asia.'),
(165,'¿Cuál es la capital de Australia?','Sídney','Melbourne','Canberra','Perth','C','Geografía','Fácil','Canberra es la capital de Australia.'),
(166,'¿En qué continente está el desierto del Sahara?','Asia','África','Oceanía','América','B','Geografía','Fácil','El Sahara se encuentra en el norte de África.'),
(167,'¿Qué país tiene forma aproximada de bota?','Italia','Grecia','Portugal','Chile','A','Geografía','Fácil','La península italiana tiene una forma característica de bota.'),
(168,'¿Cuál es la montaña más alta sobre el nivel del mar?','K2','Everest','Mont Blanc','Aconcagua','B','Geografía','Fácil','El Everest alcanza la mayor altitud sobre el nivel del mar.'),
(169,'¿Qué estrecho separa España de África?','Bósforo','Gibraltar','Magallanes','Malaca','B','Geografía','Fácil','El estrecho de Gibraltar separa Europa de África.'),
(170,'¿Cuál es la capital de Japón?','Kioto','Osaka','Tokio','Hiroshima','C','Geografía','Fácil','Tokio es la capital de Japón.'),
(171,'¿Qué protocolo se utiliza para transferir páginas web?','HTTP','FTP','SMTP','SSH','A','Tecnología','Fácil','HTTP es el protocolo base para la transferencia de páginas web.'),
(172,'¿Qué significa CPU?','Central Processing Unit','Computer Personal User','Core Program Utility','Central Program Upload','A','Tecnología','Fácil','CPU significa Central Processing Unit.'),
(173,'¿Qué lenguaje se utiliza principalmente para estructurar páginas web?','HTML','SQL','Python','Bash','A','Tecnología','Fácil','HTML estructura el contenido de las páginas web.'),
(174,'¿Qué sistema controla el código fuente de este proyecto?','Git','FTP','DNS','SMTP','A','Tecnología','Fácil','Git es un sistema de control de versiones.'),
(175,'¿Qué empresa desarrolla Android?','Google','Adobe','IBM','Nintendo','A','Tecnología','Fácil','Google desarrolla Android a través del proyecto Android.'),
(176,'¿Qué significa URL?','Uniform Resource Locator','Universal Runtime Link','User Routing Language','Unified Resource Login','A','Tecnología','Medio','URL significa Uniform Resource Locator.'),
(177,'¿Qué tecnología permite ejecutar código JavaScript en el servidor?','Node.js','Photoshop','Docker Compose','Excel','A','Tecnología','Fácil','Node.js permite ejecutar JavaScript fuera del navegador.'),
(178,'¿Qué formato se utiliza habitualmente para intercambiar datos estructurados?','JSON','MP3','JPEG','WAV','A','Tecnología','Fácil','JSON es un formato habitual para intercambio de datos estructurados.'),
(179,'¿Qué componente almacena datos de forma persistente en un ordenador?','RAM','SSD','CPU','GPU','B','Tecnología','Fácil','Un SSD almacena datos de forma persistente.'),
(180,'¿Qué significa API?','Application Programming Interface','Advanced Program Internet','Application Personal Index','Automated Protocol Input','A','Tecnología','Medio','API significa Application Programming Interface.'),
(181,'¿Quién compuso la Novena Sinfonía?','Mozart','Beethoven','Bach','Vivaldi','B','Música','Fácil','La Novena Sinfonía fue compuesta por Ludwig van Beethoven.'),
(182,'¿Qué instrumento tiene teclas blancas y negras y suele tener 88 teclas?','Violín','Piano','Flauta','Trompeta','B','Música','Fácil','Un piano moderno suele tener 88 teclas.'),
(183,'¿Qué compositor escribió Las cuatro estaciones?','Vivaldi','Chopin','Brahms','Haydn','A','Música','Fácil','Las cuatro estaciones fueron compuestas por Antonio Vivaldi.'),
(184,'¿Qué banda publicó el álbum Abbey Road?','The Beatles','The Rolling Stones','Queen','U2','A','Música','Fácil','Abbey Road es un álbum de The Beatles.'),
(185,'¿Qué instrumento pertenece a la familia de cuerda frotada?','Violín','Trompeta','Clarinete','Timbal','A','Música','Fácil','El violín es un instrumento de cuerda frotada.'),
(186,'¿Qué término indica una ejecución musical muy suave?','Forte','Piano','Allegro','Presto','B','Música','Medio','En dinámica musical, piano indica una ejecución suave.'),
(187,'¿Qué cantante lanzó el álbum Back to Black?','Amy Winehouse','Adele','Dido','Norah Jones','A','Música','Fácil','Back to Black es un álbum de Amy Winehouse.'),
(188,'¿Qué familia incluye trompeta y trombón?','Cuerda','Viento metal','Percusión','Teclado','B','Música','Fácil','La trompeta y el trombón son instrumentos de viento metal.'),
(189,'¿Qué compositor es conocido por El lago de los cisnes?','Tchaikovsky','Mahler','Liszt','Wagner','A','Música','Medio','El lago de los cisnes es un ballet de Tchaikovsky.'),
(190,'¿Cuántas notas distintas tiene la escala diatónica básica?','5','6','7','8','C','Música','Fácil','La escala diatónica básica tiene siete notas distintas.'),
(191,'¿Quién pintó La Gioconda?','Leonardo da Vinci','Miguel Ángel','Rafael','Velázquez','A','Arte','Fácil','La Gioconda fue pintada por Leonardo da Vinci.'),
(192,'¿En qué museo se encuentra la Mona Lisa?','Prado','Louvre','Uffizi','Hermitage','B','Arte','Fácil','La Mona Lisa se conserva en el Louvre de París.'),
(193,'¿Qué artista pintó Guernica?','Picasso','Dalí','Miró','Goya','A','Arte','Fácil','Guernica fue pintado por Pablo Picasso.'),
(194,'¿Qué movimiento artístico se asocia con Claude Monet?','Cubismo','Impresionismo','Surrealismo','Barroco','B','Arte','Fácil','Claude Monet fue una figura destacada del impresionismo.'),
(195,'¿Quién pintó Las meninas?','Velázquez','El Greco','Goya','Murillo','A','Arte','Fácil','Las meninas fue pintado por Diego Velázquez.'),
(196,'¿Qué artista creó La persistencia de la memoria?','Salvador Dalí','Joan Miró','Pablo Picasso','Edvard Munch','A','Arte','Fácil','La persistencia de la memoria es una obra de Salvador Dalí.'),
(197,'¿Qué estilo arquitectónico caracteriza muchas catedrales medievales con arcos apuntados?','Gótico','Románico','Neoclásico','Rococó','A','Arte','Medio','El gótico utiliza habitualmente arcos apuntados y grandes vidrieras.'),
(198,'¿Qué pintor español realizó Los fusilamientos del 3 de mayo?','Goya','Velázquez','Picasso','Sorolla','A','Arte','Medio','Francisco de Goya pintó Los fusilamientos del 3 de mayo.'),
(199,'¿Qué técnica consiste en pintar sobre yeso húmedo?','Fresco','Collage','Grabado','Acuarela','A','Arte','Medio','El fresco se pinta sobre una capa de yeso húmedo.'),
(200,'¿Qué escultor creó El pensador?','Rodin','Bernini','Donatello','Canova','A','Arte','Fácil','El pensador es una escultura de Auguste Rodin.'),
(201,'¿Quién escribió Don Quijote de la Mancha?','Miguel de Cervantes','Lope de Vega','Quevedo','Calderón de la Barca','A','Literatura','Fácil','Don Quijote de la Mancha fue escrito por Miguel de Cervantes.'),
(202,'¿Qué novela comienza con la familia Buendía?','Cien años de soledad','La Regenta','Rayuela','Fortunata y Jacinta','A','Literatura','Medio','La familia Buendía protagoniza Cien años de soledad.'),
(203,'¿Quién escribió Romeo y Julieta?','William Shakespeare','Charles Dickens','Oscar Wilde','George Orwell','A','Literatura','Fácil','Romeo y Julieta es una obra de William Shakespeare.'),
(204,'¿Qué autor creó al detective Sherlock Holmes?','Arthur Conan Doyle','Agatha Christie','Jules Verne','H. G. Wells','A','Literatura','Fácil','Sherlock Holmes fue creado por Arthur Conan Doyle.'),
(205,'¿Qué novela escribió George Orwell sobre una sociedad totalitaria?','1984','Ulises','Madame Bovary','Moby Dick','A','Literatura','Fácil','1984 es una novela distópica de George Orwell.'),
(206,'¿Quién escribió La metamorfosis?','Franz Kafka','Thomas Mann','Hermann Hesse','Stefan Zweig','A','Literatura','Fácil','La metamorfosis fue escrita por Franz Kafka.'),
(207,'¿Qué poeta chileno ganó el Nobel de Literatura en 1971?','Pablo Neruda','Gabriela Mistral','Nicanor Parra','Vicente Huidobro','A','Literatura','Medio','Pablo Neruda recibió el Nobel de Literatura en 1971.'),
(208,'¿Qué novela tiene como protagonista al capitán Ahab?','Moby Dick','Robinson Crusoe','La isla del tesoro','Drácula','A','Literatura','Medio','El capitán Ahab persigue a Moby Dick en la novela de Herman Melville.'),
(209,'¿Qué autora creó al detective Hércules Poirot?','Agatha Christie','Virginia Woolf','Jane Austen','Mary Shelley','A','Literatura','Fácil','Agatha Christie creó a Hércules Poirot.'),
(210,'¿Qué obra de Dante describe un viaje por Infierno, Purgatorio y Paraíso?','La divina comedia','El Decamerón','Fausto','El príncipe','A','Literatura','Medio','La divina comedia narra ese viaje alegórico.'),
(211,'¿Qué país es conocido por tener forma de hexágono en representaciones geográficas?','Francia','España','Italia','Polonia','A','Cultura general','Fácil','Francia continental se describe a menudo como un hexágono.'),
(212,'¿Cuántos días tiene un año bisiesto?','364','365','366','367','C','Cultura general','Fácil','Un año bisiesto tiene 366 días.'),
(213,'¿Qué planeta es conocido como el planeta rojo?','Venus','Marte','Júpiter','Saturno','B','Cultura general','Fácil','Marte recibe el nombre de planeta rojo por el aspecto de su superficie.'),
(214,'¿Cuántos lados tiene un hexágono?','5','6','7','8','B','Cultura general','Fácil','Un hexágono tiene seis lados.'),
(215,'¿Qué idioma tiene más hablantes nativos aproximadamente?','Español','Inglés','Chino mandarín','Francés','C','Cultura general','Medio','El chino mandarín es el idioma con más hablantes nativos.'),
(216,'¿Qué metal es líquido a temperatura ambiente?','Hierro','Mercurio','Cobre','Aluminio','B','Cultura general','Fácil','El mercurio es líquido a temperatura ambiente.'),
(217,'¿Cuántos minutos tiene una hora?','30','45','60','90','C','Cultura general','Fácil','Una hora tiene 60 minutos.'),
(218,'¿Qué país tiene como capital a Lisboa?','España','Portugal','Italia','Grecia','B','Cultura general','Fácil','Lisboa es la capital de Portugal.'),
(219,'¿Qué instrumento se utiliza para medir la temperatura?','Barómetro','Termómetro','Higrómetro','Anemómetro','B','Cultura general','Fácil','El termómetro mide la temperatura.'),
(220,'¿Qué color se obtiene al mezclar azul y amarillo en pintura tradicional?','Rojo','Verde','Naranja','Violeta','B','Cultura general','Fácil','En mezcla sustractiva tradicional de pigmentos, azul y amarillo producen verde.')
AS v(id,pregunta,opcion_a,opcion_b,opcion_c,opcion_d,correcta,categoria,dificultad,explicacion)
WHERE NOT EXISTS (SELECT 1 FROM workspace.quiz.preguntas p WHERE p.id = v.id);
